import user1 from "@/assets/images/users/user-1.jpg";
import user2 from "@/assets/images/users/user-2.jpg";
import user3 from "@/assets/images/users/user-3.jpg";
import user4 from "@/assets/images/users/user-4.jpg";
import user5 from "@/assets/images/users/user-5.jpg";
import user6 from "@/assets/images/users/user-6.jpg";

export const tableData = [
  {
    id: 1,
    age: 82,
    first_name: "سارا",
    last_name: "صدر",
    email: "dharling0@rediff.com",
    gender: "زن",
    phone: "232(152)707-0110",
    ccupation: "مشاور مالی",
    img: user1,
  },
  {
    id: 2,
    age: 89,
    first_name: "امیر",
    last_name: "وحیدی",
    email: "bllewellin1@example.com",
    gender: "مرد",
    phone: "420(169)218-1769",
    ccupation: "کمک بازاریابی",
    img: user2,
  },
  {
    id: 3,
    age: 28,
    first_name: "نیکا",
    last_name: "رستمی",
    email: "rcarbry2@prlog.org",
    gender: "چندجنسیتی",
    phone: "86(958)204-4491",
    ccupation: "مهندس سیستم‌های مکانیکی",
    img: user3,
  },
  {
    id: 4,
    age: 20,
    first_name: "کیانا",
    last_name: "احمدی",
    email: "bhacun3@xinhuanet.com",
    gender: "مرد",
    phone: "86(974)709-5254",
    ccupation: "کمک تحقیقاتی IV",
    img: user4,
  },
  {
    id: 5,
    age: 2,
    first_name: "مهسا",
    last_name: "کریمی",
    email: "egarstang4@miitbeian.gov.cn",
    gender: "زن",
    phone: "55(644)175-6748",
    ccupation: "تحلیل‌گر توسعه سیستم‌های کسب‌وکار",
    img: user5,
  },
  {
    id: 6,
    age: 98,
    first_name: "سمیرا",
    last_name: "سلطانی",
    email: "ddopson5@examiner.com",
    gender: "زن",
    phone: "51(186)560-8480",
    ccupation: "حسابدار هزینه",
    img: user6,
  },
  {
    id: 7,
    age: 17,
    first_name: "روژان",
    last_name: "سلیمانی",
    email: "cponter6@loc.gov",
    gender: "زن",
    phone: "1(941)734-6255",
    ccupation: "تحلیل‌گر بودجه/حسابداری II",
    img: user1,
  },
  {
    id: 8,
    age: 85,
    first_name: "سعید",
    last_name: "جوادی",
    email: "vcrispin7@dailymotion.com",
    gender: "مرد",
    phone: "380(627)884-8734",
    ccupation: "مدیر پروژه",
    img: user2,
  },
  {
    id: 9,
    age: 77,
    first_name: "رضا",
    last_name: "رضایی",
    email: "gsutlieff8@engadget.com",
    gender: "مرد",
    phone: "386(374)937-6305",
    ccupation: "مسئول استخدام",
    img: user3,
  },
  {
    id: 10,
    age: 23,
    first_name: "لیلا",
    last_name: "Smith",
    email: "nblick9@usa.gov",
    gender: "زن",
    phone: "998(884)893-6477",
    ccupation: "مدیر منابع انسانی",
    img: user4,
  },
  {
    id: 11,
    age: 2,
    first_name: "امیرعلی",
    last_name: "زمانی",
    email: "ndonisoa@dropbox.com",
    gender: "مرد",
    phone: "62(891)114-3443",
    ccupation: "مدیر عامل",
    img: user5,
  },
  {
    id: 12,
    age: 3,
    first_name: "آرمین",
    last_name: "اصفهانی",
    email: "eespinasb@over-blog.com",
    gender: "مرد",
    phone: "62(564)280-1360",
    ccupation: "تحلیل‌گر مالی ارشد",
    img: user6,
  },
  {
    id: 13,
    age: 66,
    first_name: "سام",
    last_name: "جمالی",
    email: "naglionec@epa.gov",
    gender: "مرد",
    phone: "57(354)171-9855",
    ccupation: "تحلیل‌گر مالی ارشد",
    img: user1,
  },
  {
    id: 14,
    age: 2,
    first_name: "نازنین",
    last_name: "مصباح",
    email: "nmabbsd@elegantthemes.com",
    gender: "زن",
    phone: "63(963)373-2874",
    ccupation: "اپراتور",
    img: user2,
  },
  {
    id: 15,
    age: 95,
    first_name: "علیرضا",
    last_name: "برمک",
    email: "ubramforde@seesaa.net",
    gender: "مرد",
    phone: "55(546)435-7304",
    ccupation: "برنامه‌نویس II",
    img: user3,
  },
  {
    id: 16,
    age: 58,
    first_name: "مهران",
    last_name: "گرم",
    email: "egarmf@engadget.com",
    gender: "زن",
    phone: "591(180)907-2249",
    ccupation: "کارشناس حسابداری",
    img: user4,
  },
  {
    id: 17,
    age: 86,
    first_name: "امین",
    last_name: "نیک‌نژاد",
    email: "hrunnallsg@dailymotion.com",
    gender: "مرد",
    phone: "30(515)278-6344",
    ccupation: "تحلیل‌گر بودجه/حسابداری II",
    img: user5,
  },
  {
    id: 18,
    age: 60,
    first_name: "مرجان",
    last_name: "میری",
    email: "mmaryeth@dagondesign.com",
    gender: "زن",
    phone: "27(660)562-5635",
    ccupation: "کارشناس اجرایی جوان",
    img: user6,
  },
  {
    id: 19,
    age: 16,
    first_name: "فرشید",
    last_name: "کریمی",
    email: "rcretneyi@cmu.edu",
    gender: "مرد",
    phone: "374(646)574-6654",
    ccupation: "مهندس شیمی",
    img: user1,
  },
  {
    id: 20,
    age: 42,
    first_name: "سعید",
    last_name: "نروپ",
    email: "dnarupj@dagondesign.com",
    gender: "مرد",
    phone: "7(964)301-2278",
    ccupation: "پرستار تخصصی",
    img: user2,
  },
  {
    id: 21,
    age: 27,
    first_name: "مهرداد",
    last_name: "رضایی",
    email: "odunnek@cnbc.com",
    gender: "مرد",
    phone: "1(910)450-9780",
    ccupation: "هماهنگ‌کننده داده",
    img: user3,
  },
  {
    id: 22,
    age: 47,
    first_name: "مریم",
    last_name: "نوزولی",
    email: "jnozzoliil@stumbleupon.com",
    gender: "زن",
    phone: "62(567)910-7256",
    ccupation: "پرستار ثبت‌شده",
    img: user4,
  },
  {
    id: 23,
    age: 72,
    first_name: "ناهید",
    last_name: "گریوری",
    email: "ngrivorim@delicious.com",
    gender: "زن",
    phone: "7(870)757-4318",
    ccupation: "نماینده فروش",
    img: user5,
  },
  {
    id: 24,
    age: 89,
    first_name: "محمد",
    last_name: "اصغری",
    email: "msnoddenn@ucoz.ru",
    gender: "مرد",
    phone: "82(582)574-1970",
    ccupation: "کارشناس استخدام",
    img: user6,
  },
  {
    id: 25,
    age: 62,
    first_name: "معصومه",
    last_name: "نانونی",
    email: "gnannonio@ihg.com",
    gender: "زن",
    phone: "48(356)235-7306",
    ccupation: "فروشنده ارشد",
    img: user1,
  },
  {
    id: 26,
    age: 23,
    first_name: "سحر",
    last_name: "جانوس",
    email: "kjanousp@liveinternet.ru",
    gender: "زن",
    phone: "33(312)747-9116",
    ccupation: "متخصص گفتار",
    img: user2,
  },
  {
    id: 27,
    age: 100,
    first_name: "حمید",
    last_name: "مک‌آلستر",
    email: "hmacallesterq@constantcontact.com",
    gender: "مرد",
    phone: "62(416)665-0619",
    ccupation: "هماهنگ‌کننده حساب",
    img: user3,
  },
  {
    id: 28,
    age: 85,
    first_name: "مهدی",
    last_name: "مانسی",
    email: "mmunseyr@spiegel.de",
    gender: "مرد",
    phone: "967(713)722-9345",
    ccupation: "ویراستار ارشد",
    img: user4,
  },
  {
    id: 29,
    age: 39,
    first_name: "رضا",
    last_name: "اینوود",
    email: "tinwoods@alexa.com",
    gender: "مرد",
    phone: "998(291)785-1422",
    ccupation: "کارشناس حقوقی",
    img: user5,
  },
  {
    id: 30,
    age: 59,
    first_name: "سید",
    last_name: "اوندل",
    email: "kovendalet@telegraph.co.uk",
    gender: "مرد",
    phone: "81(977)473-0581",
    ccupation: "متخصص محیط زیست",
    img: user6,
  },
  {
    id: 31,
    age: 43,
    first_name: "وولف",
    last_name: "واناه",
    email: "wvannahu@godaddy.com",
    gender: "مرد",
    phone: "48(938)552-5576",
    ccupation: "تحلیلگر مالی",
    img: user1,
  },
  {
    id: 32,
    age: 33,
    first_name: "لویی",
    last_name: "استراسمیر",
    email: "lstaresmearev@eventbrite.com",
    gender: "مرد",
    phone: "66(971)191-0397",
    ccupation: "آمارشناس زیست‌شناسی IV",
    img: user2,
  },
  {
    id: 33,
    age: 30,
    first_name: "اودل",
    last_name: "مینرو",
    email: "ominerow@irs.gov",
    gender: "مرد",
    phone: "62(187)718-2690",
    ccupation: "مدیر فروش",
    img: user3,
  },
  {
    id: 34,
    age: 16,
    first_name: "گاستون",
    last_name: "رادجلی",
    email: "grudgleyx@mozilla.com",
    gender: "مرد",
    phone: "54(491)426-6076",
    ccupation: "مهندس طراحی سرشاخه",
    img: user4,
  },
  {
    id: 35,
    age: 55,
    first_name: "وین",
    last_name: "رناک",
    email: "wrenacy@illinois.edu",
    gender: "مرد",
    phone: "7(719)471-4771",
    ccupation: "مدیر پایگاه داده I",
    img: user5,
  },
  {
    id: 36,
    age: 46,
    first_name: "تیمی",
    last_name: "روبوتهام",
    email: "trobothamz@xing.com",
    gender: "مرد",
    phone: "63(132)653-1655",
    ccupation: "مدیر استخدام",
    img: user6,
  },
  {
    id: 37,
    age: 33,
    first_name: "ویندهام",
    last_name: "دودمن",
    email: "wdudman10@smh.com.au",
    gender: "مرد",
    phone: "86(695)839-0433",
    ccupation: "تحلیلگر مالی ارشد",
    img: user1,
  },
  {
    id: 38,
    age: 74,
    first_name: "آلین",
    last_name: "نوری",
    email: "anoury11@soup.io",
    gender: "زن",
    phone: "351(222)474-2030",
    ccupation: "همکار پژوهشی",
    img: user2,
  },
  {
    id: 39,
    age: 74,
    first_name: "آلین",
    last_name: "نوری",
    email: "anoury11@soup.io",
    gender: "زن",
    phone: "351(222)474-2030",
    ccupation: "همکار پژوهشی",
    img: user2,
  },
  {
    id: 40,
    age: 74,
    first_name: "آلین",
    last_name: "نوری",
    email: "anoury11@soup.io",
    gender: "زن",
    phone: "351(222)474-2030",
    ccupation: "همکار پژوهشی",
    img: user2,
  },
  {
    id: 41,
    age: 59,
    first_name: "اردا",
    last_name: "فرین",
    email: "efrayne14@moonfruit.com",
    gender: "زن",
    phone: "86(502)895-4971",
    ccupation: "آمارشناس زیست‌شناسی I",
    img: user5,
  },
  {
    id: 42,
    age: 20,
    first_name: "جولیتا",
    last_name: "سرلس",
    email: "gserrels15@pbs.org",
    gender: "زن",
    phone: "86(626)869-8255",
    ccupation: "کارشناس اجتماعی",
    img: user6,
  },
  {
    id: 43,
    age: 3,
    first_name: "شیلا",
    last_name: "سیمونس",
    email: "ssymones16@indiegogo.com",
    gender: "زن",
    phone: "353(823)187-8422",
    ccupation: "دستیار اداری I",
    img: user1,
  },
  {
    id: 44,
    age: 40,
    first_name: "توروالد",
    last_name: "رابجنت",
    email: "trobjant17@mapy.cz",
    gender: "مرد",
    phone: "66(792)606-7511",
    ccupation: "مهندس سیستم‌های مکانیکی",
    img: user2,
  },
  {
    id: 45,
    age: 41,
    first_name: "پالتا",
    last_name: "هورسوود",
    email: "phorsewood18@yahoo.co.jp",
    gender: "زن",
    phone: "62(413)578-6139",
    ccupation: "دستیار حقوقی",
    img: user3,
  },
  {
    id: 46,
    age: 21,
    first_name: "آدان",
    last_name: "ناردروپ",
    email: "anardrup19@discovery.com",
    gender: "زن",
    phone: "7(731)243-8504",
    ccupation: "دستیار اداری IV",
    img: user4,
  },
  {
    id: 47,
    age: 94,
    first_name: "کلئوپاترا",
    last_name: "روبنس",
    email: "crobens1a@bluehost.com",
    gender: "زن",
    phone: "86(468)199-8951",
    ccupation: "آمارشناس زیست‌شناسی I",
    img: user5,
  },
  {
    id: 48,
    age: 19,
    first_name: "گیلمت",
    last_name: "گهرینگ",
    email: "ggehring1b@exblog.jp",
    gender: "زن",
    phone: "385(277)272-7058",
    ccupation: "نماینده حساب IV",
    img: user6,
  },
  {
    id: 49,
    age: 51,
    first_name: "لئورا",
    last_name: "مودلینگ",
    email: "lmaudling1c@topsy.com",
    gender: "زن",
    phone: "54(565)109-8803",
    ccupation: "دستیار فیزیوتراپی",
    img: user1,
  },
  {
    id: 50,
    age: 51,
    first_name: "لئورا",
    last_name: "مودلینگ",
    email: "lmaudling1c@topsy.com",
    gender: "زن",
    phone: "54(565)109-8803",
    ccupation: "دستیار فیزیوتراپی",
    img: user2,
  },
];

import customer1 from "@/assets/images/all-img/customer_1.png";
export const advancedTable = [
  {
    id: 1,
    order: 951,
    customer: {
      name: "علی محمدی",
      image: customer1,
    },
    date: "3/26/1402",
    quantity: 13,
    amount: "1779.53 تومان",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 2,
    order: 238,
    customer: {
      name: "مریم محمدی",
      image: customer1,
    },
    date: "2/6/1402",
    quantity: 13,
    amount: "تومان 2215.78",
    status: "معوق",
    action: null,
  },
  {
    id: 3,
    order: 339,
    customer: {
      name: "محمد رضایی",
      image: customer1,
    },
    date: "9/6/1401",
    quantity: 1,
    amount: "تومان 3183.60",
    status: "معوق",
    action: null,
  },
  {
    id: 4,
    order: 365,
    customer: {
      name: "فاطمه احمدی",
      image: customer1,
    },
    date: "11/7/1401",
    quantity: 13,
    amount: "تومان 2587.86",
    status: "لغو شده",
    action: null,
  },
  {
    id: 5,
    order: 513,
    customer: {
      name: "امیر عباسی",
      image: customer1,
    },
    date: "5/6/1402",
    quantity: 12,
    amount: "تومان 3840.73",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 6,
    order: 534,
    customer: {
      name: "نیلوفر سلطانی",
      image: customer1,
    },
    date: "2/14/1402",
    quantity: 12,
    amount: "تومان 4764.18",
    status: "لغو شده",
    action: null,
  },
  {
    id: 7,
    order: 77,
    customer: {
      name: "رضا محمدی",
      image: customer1,
    },
    date: "7/30/1402",
    quantity: 6,
    amount: "تومان 2875.05",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 8,
    order: 238,
    customer: {
      name: "محمد حسینی",
      image: customer1,
    },
    date: "6/30/1402",
    quantity: 9,
    amount: "تومان 2491.02",
    status: "معوق",
    action: null,
  },
  {
    id: 9,
    order: 886,
    customer: {
      name: "نازنین نوری",
      image: customer1,
    },
    date: "8/9/1402",
    quantity: 8,
    amount: "تومان 3006.95",
    status: "معوق",
    action: null,
  },
  {
    id: 10,
    order: 3,
    customer: {
      name: "علی رضوانی",
      image: customer1,
    },
    date: "8/4/1402",
    quantity: 12,
    amount: "تومان 2160.32",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 11,
    order: 198,
    customer: {
      name: "سارا محمدی",
      image: customer1,
    },
    date: "4/5/1402",
    quantity: 8,
    amount: "تومان 1272.66",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 12,
    order: 829,
    customer: {
      name: "آرمان عباسی",
      image: customer1,
    },
    date: "8/9/1402",
    quantity: 2,
    amount: "تومان 4327.86",
    status: "لغو شده",
    action: null,
  },
  {
    id: 13,
    order: 595,
    customer: {
      name: "آرزو علوی",
      image: customer1,
    },
    date: "2/10/1402",
    quantity: 11,
    amount: "تومان 3671.81",
    status: "لغو شده",
    action: null,
  },
  {
    id: 14,
    order: 374,
    customer: {
      name: "مینا نواب",
      image: customer1,
    },
    date: "2/10/1402",
    quantity: 2,
    amount: "تومان 3401.82",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 15,
    order: 32,
    customer: {
      name: "الهه رضوی",
      image: customer1,
    },
    date: "5/20/1402",
    quantity: 4,
    amount: "تومان 2387.49",
    status: "لغو شده",
    action: null,
  },
  {
    id: 16,
    order: 89,
    customer: {
      name: "مهدی صدر",
      image: customer1,
    },
    date: "5/3/1402",
    quantity: 15,
    amount: "تومان 4236.61",
    status: "معوق",
    action: null,
  },
  {
    id: 17,
    order: 912,
    customer: {
      name: "محمد محمدیان",
      image: customer1,
    },
    date: "10/31/1401",
    quantity: 11,
    amount: "تومان 2975.66",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 18,
    order: 621,
    customer: {
      name: "نگین نوری",
      image: customer1,
    },
    date: "1/13/1402",
    quantity: 5,
    amount: "تومان 4576.13",
    status: "لغو شده",
    action: null,
  },
  {
    id: 19,
    order: 459,
    customer: {
      name: "زهرا احمدی",
      image: customer1,
    },
    date: "6/14/1402",
    quantity: 5,
    amount: "تومان 1276.56",
    status: "لغو شده",
    action: null,
  },
  {
    id: 20,
    order: 108,
    customer: {
      name: "علی حسینی",
      image: customer1,
    },
    date: "10/8/1401",
    quantity: 4,
    amount: "تومان 1078.64",
    status: "معوق",
    action: null,
  },

  {
    id: 21,
    order: 492,
    customer: {
      name: "مریم رضایی",
      image: customer1,
    },
    date: "11/17/1401",
    quantity: 9,
    amount: "تومان 1678.19",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 22,
    order: 42,
    customer: {
      name: "ناهید محمدی",
      image: customer1,
    },
    date: "4/4/1402",
    quantity: 9,
    amount: "تومان 1822.02",
    status: "لغو شده",
    action: null,
  },
  {
    id: 23,
    order: 841,
    customer: {
      name: "مینا عبدی",
      image: customer1,
    },
    date: "3/21/1402",
    quantity: 5,
    amount: "تومان 1578.39",
    status: "معوق",
    action: null,
  },
  {
    id: 24,
    order: 561,
    customer: {
      name: "پریسا کریمی",
      image: customer1,
    },
    date: "6/18/1402",
    quantity: 12,
    amount: "تومان 2130.49",
    status: "لغو شده",
    action: null,
  },
  {
    id: 25,
    order: 720,
    customer: {
      name: "راحله صادقی",
      image: customer1,
    },
    date: "8/15/1402",
    quantity: 8,
    amount: "تومان 3721.11",
    status: "معوق",
    action: null,
  },
  {
    id: 26,
    order: 309,
    customer: {
      name: "نازنین جعفری",
      image: customer1,
    },
    date: "4/28/1402",
    quantity: 8,
    amount: "تومان 4683.45",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 27,
    order: 24,
    customer: {
      name: "فاطمه حسینی",
      image: customer1,
    },
    date: "9/6/1401",
    quantity: 7,
    amount: "تومان 2863.71",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 28,
    order: 518,
    customer: {
      name: "سارا احمدی",
      image: customer1,
    },
    date: "9/11/1401",
    quantity: 4,
    amount: "تومان 3879.41",
    status: "لغو شده",
    action: null,
  },
  {
    id: 29,
    order: 98,
    customer: {
      name: "ملیکا رحمانی",
      image: customer1,
    },
    date: "1/27/1402",
    quantity: 5,
    amount: "تومان 4660.81",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 30,
    order: 940,
    customer: {
      name: "مینا علیزاده",
      image: customer1,
    },
    date: "9/16/1401",
    quantity: 6,
    amount: "تومان 4800.75",
    status: "معوق",
    action: null,
  },
  {
    id: 31,
    order: 925,
    customer: {
      name: "لیلا رضایی",
      image: customer1,
    },
    date: "1/8/1402",
    quantity: 1,
    amount: "تومان 2299.05",
    status: "لغو شده",
    action: null,
  },
  {
    id: 32,
    order: 122,
    customer: {
      name: "سمیرا صمدی",
      image: customer1,
    },
    date: "11/18/1401",
    quantity: 1,
    amount: "تومان 3578.02",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 33,
    order: 371,
    customer: {
      name: "نگین حسینی",
      image: customer1,
    },
    date: "3/30/1402",
    quantity: 13,
    amount: "تومان 1996.06",
    status: "لغو شده",
    action: null,
  },
  {
    id: 34,
    order: 296,
    customer: {
      name: "زهرا اکبری",
      image: customer1,
    },
    date: "11/13/1401",
    quantity: 5,
    amount: "تومان 2749.00",
    status: "معوق",
    action: null,
  },
  {
    id: 35,
    order: 887,
    customer: {
      name: "مرضیه علیزاده",
      image: customer1,
    },
    date: "12/7/1401",
    quantity: 11,
    amount: "تومان 4353.01",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 36,
    order: 30,
    customer: {
      name: "فرزانه حسینی",
      image: customer1,
    },
    date: "9/9/1401",
    quantity: 15,
    amount: "تومان 3252.37",
    status: "معوق",
    action: null,
  },
  {
    id: 37,
    order: 365,
    customer: {
      name: "نیلوفر احمدی",
      image: customer1,
    },
    date: "2/12/1402",
    quantity: 5,
    amount: "تومان 4044.10",
    status: "معوق",
    action: null,
  },
  {
    id: 38,
    order: 649,
    customer: {
      name: "ناهید کریمی",
      image: customer1,
    },
    date: "3/6/1402",
    quantity: 5,
    amount: "تومان 3859.92",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 39,
    order: 923,
    customer: {
      name: "لاله محمدی",
      image: customer1,
    },
    date: "7/25/1402",
    quantity: 14,
    amount: "تومان 1652.47",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 40,
    order: 423,
    customer: {
      name: "شیوا مهرابی",
      image: customer1,
    },
    date: "3/2/1402",
    quantity: 8,
    amount: "تومان 2700.12",
    status: "لغو شده",
    action: null,
  },

  {
    id: 41,
    order: 703,
    customer: {
      name: "مریم صادقی",
      image: customer1,
    },
    date: "12/8/1401",
    quantity: 8,
    amount: "تومان 4508.13",
    status: "کنسل شده",
    action: null,
  },
  {
    id: 42,
    order: 792,
    customer: {
      name: "سارا رحمانی",
      image: customer1,
    },
    date: "11/22/1401",
    quantity: 11,
    amount: "تومان 4938.04",
    status: "در حال انجام",
    action: null,
  },
  {
    id: 43,
    order: 400,
    customer: {
      name: "نازی اکبری",
      image: customer1,
    },
    date: "4/6/1402",
    quantity: 1,
    amount: "تومان 3471.32",
    status: "در حال انجام",
    action: null,
  },
  {
    id: 44,
    order: 718,
    customer: {
      name: "فاطمه حسینی",
      image: customer1,
    },
    date: "2/4/1402",
    quantity: 4,
    amount: "تومان 4011.60",
    status: "پرداخت شده",
    action: null,
  },
  {
    id: 45,
    order: 970,
    customer: {
      name: "لیلا زمانی",
      image: customer1,
    },
    date: "3/30/1402",
    quantity: 15,
    amount: "تومان 3723.64",
    status: "در حال انجام",
    action: null,
  },
  {
    id: 46,
    order: 786,
    customer: {
      name: "زهرا علوی",
      image: customer1,
    },
    date: "11/20/1401",
    quantity: 2,
    amount: "تومان 2441.15",
    status: "کنسل شده",
    action: null,
  },
  {
    id: 47,
    order: 925,
    customer: {
      name: "سمیرا کریمی",
      image: customer1,
    },
    date: "10/24/1401",
    quantity: 11,
    amount: "تومان 1196.76",
    status: "کنسل شده",
    action: null,
  },
  {
    id: 48,
    order: 929,
    customer: {
      name: "محمد رضایی",
      image: customer1,
    },
    date: "6/30/1402",
    quantity: 10,
    amount: "تومان 3579.57",
    status: "کنسل شده",
    action: null,
  },
  {
    id: 49,
    order: 377,
    customer: {
      name: "نیما محمدی",
      image: customer1,
    },
    date: "11/16/1401",
    quantity: 4,
    amount: "تومان 2657.84",
    status: "در حال انجام",
    action: null,
  },
  {
    id: 50,
    order: 661,
    customer: {
      name: "حسین میرزایی",
      image: customer1,
    },
    date: "8/15/1402",
    quantity: 6,
    amount: "تومان 2905.94",
    status: "پرداخت شده",
    action: null,
  },
];

export const homeTable = [
  {
    company: user1,
    category: "نصب پوشش آسفالتی",
    views: 343,
    revenue: "تومان 231.26",
    sales: 95,
    up: false,
  },
  {
    company: user2,
    category: "ریلینگ‌های تزئینی",
    views: 315,
    revenue: "تومان 432.81",
    sales: 197,
    up: false,
  },
  {
    company: user3,
    category: "نصب بتن آرمه و مش",
    views: 329,
    revenue: "تومان 437.65",
    sales: 137,
    up: true,
  },
  {
    company: user4,
    category: "ساخت و نصب فلزات ساختمانی و متفرقه",
    views: 336,
    revenue: "تومان 387.55",
    sales: 101,
    up: true,
  },
  {
    company: user5,
    category: "محافظت از دیوار",
    views: 375,
    revenue: "تومان 489.80",
    sales: 99,
    up: false,
  },
  {
    company: user6,
    category: "پنل‌های مارلایت (FED)",
    views: 490,
    revenue: "تومان 421.45",
    sales: 101,
    up: true,
  },
  {
    company: user1,
    category: "کفپوش اپوکسی",
    views: 433,
    revenue: "تومان 207.61",
    sales: 197,
    up: false,
  },
  {
    company: user2,
    category: "کفپوش اپوکسی",
    views: 499,
    revenue: "تومان 392.86",
    sales: 91,
    up: false,
  },
  {
    company: user3,
    category: "پنل‌های مارلایت (FED)",
    views: 441,
    revenue: "تومان 162.87",
    sales: 115,
    up: false,
  },
  {
    company: user4,
    category: "محافظت از امواج رادیویی",
    views: 415,
    revenue: "تومان 268.58",
    sales: 128,
    up: false,
  },
  {
    company: user5,
    category: "نصب روفینگ فلزی",
    views: 303,
    revenue: "تومان 369.19",
    sales: 179,
    up: false,
  },
  {
    company: user6,
    category: "محافظت از امواج رادیویی",
    views: 415,
    revenue: "تومان 420.87",
    sales: 148,
    up: false,
  },
  {
    company: user1,
    category: "گذرگاه و بلوک متفرقه",
    views: 493,
    revenue: "تومان 420.26",
    sales: 152,
    up: false,
  },
  {
    company: user2,
    category: "نصب فلزات ساختمانی و متفرقه",
    views: 498,
    revenue: "تومان 228.41",
    sales: 151,
    up: false,
  },
  {
    company: user3,
    category: "نصب دیوار حائل و سنگ‌فرش",
    views: 465,
    revenue: "تومان 140.83",
    sales: 71,
    up: false,
  },
  {
    company: user4,
    category: "نصب کارهای ساختمانی و ابزارهای مرتبط",
    views: 468,
    revenue: "تومان 475.63",
    sales: 114,
    up: false,
  },
  {
    company: user5,
    category: "نصب بتن آرمه و مش",
    views: 357,
    revenue: "تومان 415.37",
    sales: 163,
    up: false,
  },
  {
    company: user6,
    category: "عایق‌کاری و کلکسیون",
    views: 487,
    revenue: "تومان 436.53",
    sales: 170,
    up: false,
  },
  {
    company: user1,
    category: "تجهیزات سایت",
    views: 357,
    revenue: "تومان 147.36",
    sales: 71,
    up: false,
  },
  {
    company: user2,
    category: "کاپسول",
    views: 465,
    revenue: "تومان 121.67",
    sales: 78,
    up: false,
  },
  {
    company: user3,
    category: "نرده های تزئینی",
    views: 438,
    revenue: "تومان 213.25",
    sales: 155,
    up: false,
  },
  {
    company: user4,
    category: "عایق‌کاری و کلکسیون",
    views: 461,
    revenue: "تومان 186.48",
    sales: 137,
    up: false,
  },
  {
    company: user5,
    category: "مصالح ساختمانی",
    views: 423,
    revenue: "تومان 130.97",
    sales: 178,
    up: false,
  },
  {
    company: user6,
    category: "گذرگاه و بلوک متفرقه",
    views: 339,
    revenue: "تومان 255.69",
    sales: 101,
    up: false,
  },
  {
    company: user1,
    category: "تهویه و تهویه مطبوع",
    views: 361,
    revenue: "تومان 484.64",
    sales: 175,
    up: true,
  },
  {
    company: user2,
    category: "علائم خارجی",
    views: 353,
    revenue: "تومان 485.51",
    sales: 176,
    up: true,
  },
  {
    company: user3,
    category: "اطفاء حریق",
    views: 364,
    revenue: "تومان 449.45",
    sales: 136,
    up: true,
  },
  {
    company: user4,
    category: "نصب مفتول و مش",
    views: 493,
    revenue: "تومان 309.61",
    sales: 163,
    up: true,
  },
  {
    company: user5,
    category: "نصب حصار موقت، حصار تزئینی و دروازه",
    views: 393,
    revenue: "تومان 372.45",
    sales: 180,
    up: true,
  },
  {
    company: user6,
    category: "اطفاء حریق",
    views: 441,
    revenue: "تومان 470.34",
    sales: 104,
    up: false,
  },
];

export const recentOrder = [
  {
    user: {
      name: "مژده جعفری",
      image: user1,
    },
    product: "هدفون",
    invoice: "#324567",
    price: "تومان 90.99",
    status: "پرداخت شده",
  },
  {
    user: {
      name: "محمد محمدی",
      image: user2,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "سررسید",
  },
  {
    user: {
      name: "فاطمه رضایی",
      image: user3,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "در انتظار",
  },
  {
    user: {
      name: "علی رحمانی",
      image: user4,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 38.65",
    status: "لغو شده",
  },
  {
    user: {
      name: "نازنین عابدی",
      image: user5,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 178.65",
    status: "ارسال شده",
  },
  {
    user: {
      name: "حمیدرضا رضایی",
      image: user6,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 74.65",
    status: "لغو شده",
  },
  {
    user: {
      name: "زهره خدادادی",
      image: user1,
    },
    product: "هدفون",
    invoice: "#324567",
    price: "تومان 90.99",
    status: "پرداخت شده",
  },
  {
    user: {
      name: "علی اکبری",
      image: user2,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "سررسید",
  },
  {
    user: {
      name: "فاطمه محمدی",
      image: user3,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "در انتظار",
  },
  {
    user: {
      name: "مهران رحمانی",
      image: user4,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 38.65",
    status: "لغو شده",
  },
  {
    user: {
      name: "مهدی عابدی",
      image: user5,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 178.65",
    status: "ارسال شده",
  },
  {
    user: {
      name: "شهرزاد رضایی",
      image: user6,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 74.65",
    status: "لغو شده",
  },
  {
    user: {
      name: "رضا جعفری",
      image: user1,
    },
    product: "هدفون",
    invoice: "#324567",
    price: "تومان 90.99",
    status: "پرداخت شده",
  },
  {
    user: {
      name: "حسین محمدی",
      image: user2,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "سررسید",
  },
  {
    user: {
      name: "زهرا رضایی",
      image: user3,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "در انتظار",
  },
  {
    user: {
      name: "رضا رحمانی",
      image: user4,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 38.65",
    status: "لغو شده",
  },
  {
    user: {
      name: "مریم عابدی",
      image: user5,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 178.65",
    status: "ارسال شده",
  },
  {
    user: {
      name: "سارا رضایی",
      image: user6,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 74.65",
    status: "لغو شده",
  },
  {
    user: {
      name: "مهران جعفری",
      image: user1,
    },
    product: "هدفون",
    invoice: "#324567",
    price: "تومان 90.99",
    status: "پرداخت شده",
  },
  {
    user: {
      name: "فرید محمدی",
      image: user2,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "سررسید",
  },
  {
    user: {
      name: "لیلا رضایی",
      image: user3,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 78.65",
    status: "در انتظار",
  },
  {
    user: {
      name: "علی رحمانی",
      image: user4,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 38.65",
    status: "لغو شده",
  },
  {
    user: {
      name: "مریم عابدی",
      image: user5,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 178.65",
    status: "ارسال شده",
  },
  {
    user: {
      name: "علی رحمانی",
      image: user6,
    },
    product: "هدفون",
    invoice: "#4224",
    price: "تومان 74.65",
    status: "لغو شده",
  },
];

export const teamData = [
  {
    customer: {
      name: "سارا میرزایی",
      image: user1,
      deg: "طراح Ux",
    },
    status: "در حال پیشرفت",
    time: "42.5 ساعت",
    chart: null,
  },
  {
    customer: {
      name: "سارا میرزایی",
      image: user2,
      deg: "طراح Ux",
    },
    status: "تکمیل شده",
    time: "42.5 ساعت",
    chart: null,
  },
  {
    customer: {
      name: "سارا میرزایی",
      image: user3,
      deg: "طراح Ux",
    },
    status: "در حال پیشرفت",
    time: "42.5 ساعت",
    chart: null,
  },
  {
    customer: {
      name: "سارا میرزایی",
      image: user4,
      deg: "طراح Ux",
    },
    status: "تکمیل شده",
    time: "42.5 ساعت",
    chart: null,
  },
];
