# Generated by Django 4.0.1 on 2024-03-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(max_length=30),
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('hirbod', 'Hirbod'), ('province_boss', 'Province Boss'), ('province_master', 'Province Master'), ('coach', 'Coach'), ('guest', 'Guest')], default='guest', max_length=30),
        ),
    ]
